//CUSTOMER
export const CUSTOMER_REQUEST = 'CUSTOMER_REQUEST';
export const CUSTOMER_RECEIVE = 'CUSTOMER_RECEIVE';
export const CUSTOMER_SUCCESS = 'CUSTOMER_SUCCESS';
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR';
//DEVICE
export const DEVICE_TOGGLE = 'DEVICE_TOGGLE';
